// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANz1PEZj9ToRa944uzJO1nSiV4AuLQgvg',
    appId: '1:1058513152685:web:806f74f83172116902f424',
    messagingSenderId: '1058513152685',
    projectId: 'latch-374c0',
    authDomain: 'latch-374c0.firebaseapp.com',
    storageBucket: 'latch-374c0.firebasestorage.app',
    measurementId: 'G-BBBLMTS3V4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTXnYzFTcQLYUEULtMlw2bfhc6MM-jJyc',
    appId: '1:1058513152685:android:74eb8159fd0d267c02f424',
    messagingSenderId: '1058513152685',
    projectId: 'latch-374c0',
    storageBucket: 'latch-374c0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFrNJ4akzGCyKXI6eJEIZBJgW9MTNRrvc',
    appId: '1:1058513152685:ios:264419d644abea6802f424',
    messagingSenderId: '1058513152685',
    projectId: 'latch-374c0',
    storageBucket: 'latch-374c0.firebasestorage.app',
    androidClientId: '1058513152685-5j4qq0t8i6or7h6662p4k75gp1qhkea1.apps.googleusercontent.com',
    iosClientId: '1058513152685-h48jm2fhmo1j3ocj2vmg9b2rj1ad6ne0.apps.googleusercontent.com',
    iosBundleId: 'com.latch.mobile',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFrNJ4akzGCyKXI6eJEIZBJgW9MTNRrvc',
    appId: '1:1058513152685:ios:264419d644abea6802f424',
    messagingSenderId: '1058513152685',
    projectId: 'latch-374c0',
    storageBucket: 'latch-374c0.firebasestorage.app',
    iosBundleId: 'com.latch.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANz1PEZj9ToRa944uzJO1nSiV4AuLQgvg',
    appId: '1:1058513152685:web:8dd90df9b6a52c5b02f424',
    messagingSenderId: '1058513152685',
    projectId: 'latch-374c0',
    authDomain: 'latch-374c0.firebaseapp.com',
    storageBucket: 'latch-374c0.firebasestorage.app',
    measurementId: 'G-76TXE8G6NF',
  );
}
