package kotlin.reflect.jvm.internal.impl.util;

import java.util.Set;
import kotlin.collections.SetsKt;
import kotlin.jvm.internal.Intrinsics;
import kotlin.reflect.jvm.internal.impl.name.Name;
import kotlin.text.Regex;

/* JADX INFO: compiled from: OperatorNameConventions.kt */
/* JADX INFO: loaded from: classes2.dex */
public final class OperatorNameConventions {
    public static final Name AND;
    public static final Set<Name> ASSIGNMENT_OPERATIONS;
    public static final Set<Name> BINARY_OPERATION_NAMES;
    public static final Name COMPARE_TO;
    public static final Regex COMPONENT_REGEX;
    public static final Name CONTAINS;
    public static final Name DEC;
    public static final Set<Name> DELEGATED_PROPERTY_OPERATORS;
    public static final Name DIV;
    public static final Name DIV_ASSIGN;
    public static final Name EQUALS;
    public static final Name GET;
    public static final Name GET_VALUE;
    public static final Name HAS_NEXT;
    public static final Name INC;
    public static final OperatorNameConventions INSTANCE = new OperatorNameConventions();
    public static final Name INVOKE;
    public static final Name ITERATOR;
    public static final Name MINUS;
    public static final Name MINUS_ASSIGN;
    public static final Name MOD;
    public static final Name MOD_ASSIGN;
    public static final Name NEXT;
    public static final Name NOT;
    public static final Name OR;
    public static final Name PLUS;
    public static final Name PLUS_ASSIGN;
    public static final Name PROVIDE_DELEGATE;
    public static final Name RANGE_TO;
    public static final Name REM;
    public static final Name REM_ASSIGN;
    public static final Name SET;
    public static final Name SET_VALUE;
    public static final Set<Name> SIMPLE_UNARY_OPERATION_NAMES;
    public static final Name TIMES;
    public static final Name TIMES_ASSIGN;
    public static final Name TO_STRING;
    public static final Name UNARY_MINUS;
    public static final Set<Name> UNARY_OPERATION_NAMES;
    public static final Name UNARY_PLUS;

    private OperatorNameConventions() {
    }

    static {
        Name nameIdentifier = Name.identifier("getValue");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier, "identifier(\"getValue\")");
        GET_VALUE = nameIdentifier;
        Name nameIdentifier2 = Name.identifier("setValue");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier2, "identifier(\"setValue\")");
        SET_VALUE = nameIdentifier2;
        Name nameIdentifier3 = Name.identifier("provideDelegate");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier3, "identifier(\"provideDelegate\")");
        PROVIDE_DELEGATE = nameIdentifier3;
        Name nameIdentifier4 = Name.identifier("equals");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier4, "identifier(\"equals\")");
        EQUALS = nameIdentifier4;
        Name nameIdentifier5 = Name.identifier("compareTo");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier5, "identifier(\"compareTo\")");
        COMPARE_TO = nameIdentifier5;
        Name nameIdentifier6 = Name.identifier("contains");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier6, "identifier(\"contains\")");
        CONTAINS = nameIdentifier6;
        Name nameIdentifier7 = Name.identifier("invoke");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier7, "identifier(\"invoke\")");
        INVOKE = nameIdentifier7;
        Name nameIdentifier8 = Name.identifier("iterator");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier8, "identifier(\"iterator\")");
        ITERATOR = nameIdentifier8;
        Name nameIdentifier9 = Name.identifier("get");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier9, "identifier(\"get\")");
        GET = nameIdentifier9;
        Name nameIdentifier10 = Name.identifier("set");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier10, "identifier(\"set\")");
        SET = nameIdentifier10;
        Name nameIdentifier11 = Name.identifier("next");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier11, "identifier(\"next\")");
        NEXT = nameIdentifier11;
        Name nameIdentifier12 = Name.identifier("hasNext");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier12, "identifier(\"hasNext\")");
        HAS_NEXT = nameIdentifier12;
        Name nameIdentifier13 = Name.identifier("toString");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier13, "identifier(\"toString\")");
        TO_STRING = nameIdentifier13;
        COMPONENT_REGEX = new Regex("component\\d+");
        Name nameIdentifier14 = Name.identifier("and");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier14, "identifier(\"and\")");
        AND = nameIdentifier14;
        Name nameIdentifier15 = Name.identifier("or");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier15, "identifier(\"or\")");
        OR = nameIdentifier15;
        Name nameIdentifier16 = Name.identifier("inc");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier16, "identifier(\"inc\")");
        INC = nameIdentifier16;
        Name nameIdentifier17 = Name.identifier("dec");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier17, "identifier(\"dec\")");
        DEC = nameIdentifier17;
        Name nameIdentifier18 = Name.identifier("plus");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier18, "identifier(\"plus\")");
        PLUS = nameIdentifier18;
        Name nameIdentifier19 = Name.identifier("minus");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier19, "identifier(\"minus\")");
        MINUS = nameIdentifier19;
        Name nameIdentifier20 = Name.identifier("not");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier20, "identifier(\"not\")");
        NOT = nameIdentifier20;
        Name nameIdentifier21 = Name.identifier("unaryMinus");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier21, "identifier(\"unaryMinus\")");
        UNARY_MINUS = nameIdentifier21;
        Name nameIdentifier22 = Name.identifier("unaryPlus");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier22, "identifier(\"unaryPlus\")");
        UNARY_PLUS = nameIdentifier22;
        Name nameIdentifier23 = Name.identifier("times");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier23, "identifier(\"times\")");
        TIMES = nameIdentifier23;
        Name nameIdentifier24 = Name.identifier("div");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier24, "identifier(\"div\")");
        DIV = nameIdentifier24;
        Name nameIdentifier25 = Name.identifier("mod");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier25, "identifier(\"mod\")");
        MOD = nameIdentifier25;
        Name nameIdentifier26 = Name.identifier("rem");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier26, "identifier(\"rem\")");
        REM = nameIdentifier26;
        Name nameIdentifier27 = Name.identifier("rangeTo");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier27, "identifier(\"rangeTo\")");
        RANGE_TO = nameIdentifier27;
        Name nameIdentifier28 = Name.identifier("timesAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier28, "identifier(\"timesAssign\")");
        TIMES_ASSIGN = nameIdentifier28;
        Name nameIdentifier29 = Name.identifier("divAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier29, "identifier(\"divAssign\")");
        DIV_ASSIGN = nameIdentifier29;
        Name nameIdentifier30 = Name.identifier("modAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier30, "identifier(\"modAssign\")");
        MOD_ASSIGN = nameIdentifier30;
        Name nameIdentifier31 = Name.identifier("remAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier31, "identifier(\"remAssign\")");
        REM_ASSIGN = nameIdentifier31;
        Name nameIdentifier32 = Name.identifier("plusAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier32, "identifier(\"plusAssign\")");
        PLUS_ASSIGN = nameIdentifier32;
        Name nameIdentifier33 = Name.identifier("minusAssign");
        Intrinsics.checkNotNullExpressionValue(nameIdentifier33, "identifier(\"minusAssign\")");
        MINUS_ASSIGN = nameIdentifier33;
        UNARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier16, nameIdentifier17, nameIdentifier22, nameIdentifier21, nameIdentifier20});
        SIMPLE_UNARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier22, nameIdentifier21, nameIdentifier20});
        BINARY_OPERATION_NAMES = SetsKt.setOf((Object[]) new Name[]{nameIdentifier23, nameIdentifier18, nameIdentifier19, nameIdentifier24, nameIdentifier25, nameIdentifier26, nameIdentifier27});
        ASSIGNMENT_OPERATIONS = SetsKt.setOf((Object[]) new Name[]{nameIdentifier28, nameIdentifier29, nameIdentifier30, nameIdentifier31, nameIdentifier32, nameIdentifier33});
        DELEGATED_PROPERTY_OPERATORS = SetsKt.setOf((Object[]) new Name[]{nameIdentifier, nameIdentifier2, nameIdentifier3});
    }
}
